spring:    data:    mongodb:      host: localhost      port: 27017      database: custdb
        application:    name: CustomerService
server:  port: 8082   eureka:  client:    register-with-eureka: true    fetch-registry: true    service-url:      defaultZone: http://localhost:9091/eureka